---
apiVersion: nimbess.com/v1
kind: UnifiedNetworkPolicy
metadata:
  name: testpolicy
  namespace: kube-system
spec:
  l7Policies:
    - default:
        action: allow
    - urlFilter:
        action: deny
        urls:
          - www.google.com/blah/*
          - www.yahoo.com/*
          - msn.com
        podSelector:
          matchLabels:
            environment: production
        network: regionA
  podSelector:
    matchLabels:
      environment: dev
  network: devNetwork
