---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nimbess
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nimbess
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "pods/status", "services"]
    verbs: ["get", "list", "watch", "update", "create"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "get", "list", "watch", "patch", "update", "delete"]
  - apiGroups: ["*"]
    resources: ["unifiednetworkpolicies"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nimbess
roleRef:
  kind: ClusterRole
  name: nimbess
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: nimbess
    namespace: kube-system

---
apiVersion: v1
kind: Namespace
metadata:
  name: nimbess
