---
apiVersion: v1
kind: Pod
metadata:
  name: stargazer
  namespace: stargazer
spec:
  containers:
  - name: stargazer
    image: nimbess/stargazer:1
    imagePullPolicy: Never
  nodeName: kube-nonetwork-node-1
  serviceAccountName: stargazer
