---
apiVersion: v1
kind: Pod
metadata:
  name: stargazer
  namespace: kube-system
spec:
  containers:
  - name: stargazer
    image: nimbess/stargazer:1
    imagePullPolicy: Never
    env:
      - name: ETCDCTL_ENDPOINTS
        valueFrom:
          configMapKeyRef:
            name: nimbess-etcd-config
            key: etcdctl_endpoints
  # Comment out the below to let k8s select any node
  nodeName: kube-nonetwork-node-1
  serviceAccountName: stargazer
