---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nimbess-etcd-config
  namespace: kube-system
  labels:
    app: nimbess-etcd
data:
  # Add comma-separated list of node host addresses where the nimbess-etcd pods are started
  etcdctl_endpoints: "127.0.0.1:52379"
---
apiVersion: v1
kind: Service
metadata:
  name: nimbess-etcd
  namespace: kube-system
  labels:
    app: nimbess-etcd
spec:
  ports:
    - name: client
      port: 52379
      protocol: TCP
    - name: server
      port: 52380
      protocol: TCP
  selector:
    app: nimbess-etcd
---
apiVersion: v1
kind: Pod
metadata:
  name: nimbess-etcd
  namespace: kube-system
  labels:
    app: nimbess-etcd
spec:
  nodeSelector:
    node-role.kubernetes.io/master: ""
  priorityClassName: system-node-critical
  tolerations:
    - operator: Exists
      effect: NoSchedule
  containers:
  - name: nimbess-etcd
    image: k8s.gcr.io/etcd:3.3.10
    imagePullPolicy: IfNotPresent
    env:
    - name: ETCDCTL_API
      value: "3"
    - name: ETCDCTL_ENDPOINTS
      valueFrom:
        configMapKeyRef:
          name: nimbess-etcd-config
          key: etcdctl_endpoints
    command:
      - /usr/local/bin/etcd
      - --name=nimbess-etcd
      - --data-dir=/var/lib/nimbess-etcd
      - --debug
      - --advertise-client-urls=http://0.0.0.0:52379
      - --listen-client-urls=http://0.0.0.0:52379
      - --listen-peer-urls=http://0.0.0.0:52380
    ports:
      - name: client
        containerPort: 52379
        protocol: TCP
      - name: server
        containerPort: 52380
        protocol: TCP
    volumeMounts:
      - mountPath: /var/lib/nimbess-etcd
        name: etcd-data
  volumes:
    - hostPath:
        path: /var/lib/nimbess-etcd
        type: DirectoryOrCreate
      name: etcd-data
  hostNetwork: true
