---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: stargazer
  namespace: stargazer
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stargazer
  namespace: stargazer
roleRef:
  kind: Role
  name: stargazer
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: stargazer
  namespace: stargazer
