---
apiVersion: v1
kind: Pod
metadata:
  name: stargazer
  namespace: kube-system
spec:
  nodeSelector:
    node-role.kubernetes.io/master: ""
  priorityClassName: system-node-critical
  tolerations:
    - operator: Exists
      effect: NoSchedule
  containers:
  - name: stargazer
    image: nimbess/stargazer
    env:
      - name: ETCDCTL_ENDPOINTS
        valueFrom:
          configMapKeyRef:
            name: nimbess-etcd-config
            key: etcdctl_endpoints
  serviceAccountName: nimbess
  hostNetwork: true
