/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	unpv1 "github.com/nimbess/stargazer/pkg/crd/api/unp/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeUnifiedNetworkPolicies implements UnifiedNetworkPolicyInterface
type FakeUnifiedNetworkPolicies struct {
	Fake *FakeNimbessV1
	ns   string
}

var unifiednetworkpoliciesResource = schema.GroupVersionResource{Group: "nimbess", Version: "v1", Resource: "unifiednetworkpolicies"}

var unifiednetworkpoliciesKind = schema.GroupVersionKind{Group: "nimbess", Version: "v1", Kind: "UnifiedNetworkPolicy"}

// Get takes name of the unifiedNetworkPolicy, and returns the corresponding unifiedNetworkPolicy object, and an error if there is any.
func (c *FakeUnifiedNetworkPolicies) Get(name string, options v1.GetOptions) (result *unpv1.UnifiedNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(unifiednetworkpoliciesResource, c.ns, name), &unpv1.UnifiedNetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*unpv1.UnifiedNetworkPolicy), err
}

// List takes label and field selectors, and returns the list of UnifiedNetworkPolicies that match those selectors.
func (c *FakeUnifiedNetworkPolicies) List(opts v1.ListOptions) (result *unpv1.UnifiedNetworkPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(unifiednetworkpoliciesResource, unifiednetworkpoliciesKind, c.ns, opts), &unpv1.UnifiedNetworkPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &unpv1.UnifiedNetworkPolicyList{ListMeta: obj.(*unpv1.UnifiedNetworkPolicyList).ListMeta}
	for _, item := range obj.(*unpv1.UnifiedNetworkPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested unifiedNetworkPolicies.
func (c *FakeUnifiedNetworkPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(unifiednetworkpoliciesResource, c.ns, opts))

}

// Create takes the representation of a unifiedNetworkPolicy and creates it.  Returns the server's representation of the unifiedNetworkPolicy, and an error, if there is any.
func (c *FakeUnifiedNetworkPolicies) Create(unifiedNetworkPolicy *unpv1.UnifiedNetworkPolicy) (result *unpv1.UnifiedNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(unifiednetworkpoliciesResource, c.ns, unifiedNetworkPolicy), &unpv1.UnifiedNetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*unpv1.UnifiedNetworkPolicy), err
}

// Update takes the representation of a unifiedNetworkPolicy and updates it. Returns the server's representation of the unifiedNetworkPolicy, and an error, if there is any.
func (c *FakeUnifiedNetworkPolicies) Update(unifiedNetworkPolicy *unpv1.UnifiedNetworkPolicy) (result *unpv1.UnifiedNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(unifiednetworkpoliciesResource, c.ns, unifiedNetworkPolicy), &unpv1.UnifiedNetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*unpv1.UnifiedNetworkPolicy), err
}

// Delete takes name of the unifiedNetworkPolicy and deletes it. Returns an error if one occurs.
func (c *FakeUnifiedNetworkPolicies) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(unifiednetworkpoliciesResource, c.ns, name), &unpv1.UnifiedNetworkPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeUnifiedNetworkPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(unifiednetworkpoliciesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &unpv1.UnifiedNetworkPolicyList{})
	return err
}

// Patch applies the patch and returns the patched unifiedNetworkPolicy.
func (c *FakeUnifiedNetworkPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *unpv1.UnifiedNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(unifiednetworkpoliciesResource, c.ns, name, pt, data, subresources...), &unpv1.UnifiedNetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*unpv1.UnifiedNetworkPolicy), err
}
