/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	scheme "github.com/nimbess/stargazer/pkg/client/clientset/versioned/scheme"
	v1 "github.com/nimbess/stargazer/pkg/crd/api/unp/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// UnifiedNetworkPoliciesGetter has a method to return a UnifiedNetworkPolicyInterface.
// A group's client should implement this interface.
type UnifiedNetworkPoliciesGetter interface {
	UnifiedNetworkPolicies(namespace string) UnifiedNetworkPolicyInterface
}

// UnifiedNetworkPolicyInterface has methods to work with UnifiedNetworkPolicy resources.
type UnifiedNetworkPolicyInterface interface {
	Create(*v1.UnifiedNetworkPolicy) (*v1.UnifiedNetworkPolicy, error)
	Update(*v1.UnifiedNetworkPolicy) (*v1.UnifiedNetworkPolicy, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.UnifiedNetworkPolicy, error)
	List(opts metav1.ListOptions) (*v1.UnifiedNetworkPolicyList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.UnifiedNetworkPolicy, err error)
	UnifiedNetworkPolicyExpansion
}

// unifiedNetworkPolicies implements UnifiedNetworkPolicyInterface
type unifiedNetworkPolicies struct {
	client rest.Interface
	ns     string
}

// newUnifiedNetworkPolicies returns a UnifiedNetworkPolicies
func newUnifiedNetworkPolicies(c *NimbessV1Client, namespace string) *unifiedNetworkPolicies {
	return &unifiedNetworkPolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the unifiedNetworkPolicy, and returns the corresponding unifiedNetworkPolicy object, and an error if there is any.
func (c *unifiedNetworkPolicies) Get(name string, options metav1.GetOptions) (result *v1.UnifiedNetworkPolicy, err error) {
	result = &v1.UnifiedNetworkPolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("unifiednetworkpolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of UnifiedNetworkPolicies that match those selectors.
func (c *unifiedNetworkPolicies) List(opts metav1.ListOptions) (result *v1.UnifiedNetworkPolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.UnifiedNetworkPolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("unifiednetworkpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested unifiedNetworkPolicies.
func (c *unifiedNetworkPolicies) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("unifiednetworkpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a unifiedNetworkPolicy and creates it.  Returns the server's representation of the unifiedNetworkPolicy, and an error, if there is any.
func (c *unifiedNetworkPolicies) Create(unifiedNetworkPolicy *v1.UnifiedNetworkPolicy) (result *v1.UnifiedNetworkPolicy, err error) {
	result = &v1.UnifiedNetworkPolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("unifiednetworkpolicies").
		Body(unifiedNetworkPolicy).
		Do().
		Into(result)
	return
}

// Update takes the representation of a unifiedNetworkPolicy and updates it. Returns the server's representation of the unifiedNetworkPolicy, and an error, if there is any.
func (c *unifiedNetworkPolicies) Update(unifiedNetworkPolicy *v1.UnifiedNetworkPolicy) (result *v1.UnifiedNetworkPolicy, err error) {
	result = &v1.UnifiedNetworkPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("unifiednetworkpolicies").
		Name(unifiedNetworkPolicy.Name).
		Body(unifiedNetworkPolicy).
		Do().
		Into(result)
	return
}

// Delete takes name of the unifiedNetworkPolicy and deletes it. Returns an error if one occurs.
func (c *unifiedNetworkPolicies) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("unifiednetworkpolicies").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *unifiedNetworkPolicies) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("unifiednetworkpolicies").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched unifiedNetworkPolicy.
func (c *unifiedNetworkPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.UnifiedNetworkPolicy, err error) {
	result = &v1.UnifiedNetworkPolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("unifiednetworkpolicies").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
