/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	scheme "github.com/nimbess/stargazer/pkg/client/clientset/versioned/scheme"
	v1 "github.com/nimbess/stargazer/pkg/crd/api/unp/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// UnpConfigsGetter has a method to return a UnpConfigInterface.
// A group's client should implement this interface.
type UnpConfigsGetter interface {
	UnpConfigs(namespace string) UnpConfigInterface
}

// UnpConfigInterface has methods to work with UnpConfig resources.
type UnpConfigInterface interface {
	Create(*v1.UnpConfig) (*v1.UnpConfig, error)
	Update(*v1.UnpConfig) (*v1.UnpConfig, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.UnpConfig, error)
	List(opts metav1.ListOptions) (*v1.UnpConfigList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.UnpConfig, err error)
	UnpConfigExpansion
}

// unpConfigs implements UnpConfigInterface
type unpConfigs struct {
	client rest.Interface
	ns     string
}

// newUnpConfigs returns a UnpConfigs
func newUnpConfigs(c *NimbessV1Client, namespace string) *unpConfigs {
	return &unpConfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the unpConfig, and returns the corresponding unpConfig object, and an error if there is any.
func (c *unpConfigs) Get(name string, options metav1.GetOptions) (result *v1.UnpConfig, err error) {
	result = &v1.UnpConfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("unpconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of UnpConfigs that match those selectors.
func (c *unpConfigs) List(opts metav1.ListOptions) (result *v1.UnpConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.UnpConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("unpconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested unpConfigs.
func (c *unpConfigs) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("unpconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a unpConfig and creates it.  Returns the server's representation of the unpConfig, and an error, if there is any.
func (c *unpConfigs) Create(unpConfig *v1.UnpConfig) (result *v1.UnpConfig, err error) {
	result = &v1.UnpConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("unpconfigs").
		Body(unpConfig).
		Do().
		Into(result)
	return
}

// Update takes the representation of a unpConfig and updates it. Returns the server's representation of the unpConfig, and an error, if there is any.
func (c *unpConfigs) Update(unpConfig *v1.UnpConfig) (result *v1.UnpConfig, err error) {
	result = &v1.UnpConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("unpconfigs").
		Name(unpConfig.Name).
		Body(unpConfig).
		Do().
		Into(result)
	return
}

// Delete takes name of the unpConfig and deletes it. Returns an error if one occurs.
func (c *unpConfigs) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("unpconfigs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *unpConfigs) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("unpconfigs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched unpConfig.
func (c *unpConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.UnpConfig, err error) {
	result = &v1.UnpConfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("unpconfigs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
