// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultPolicy) DeepCopyInto(out *DefaultPolicy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultPolicy.
func (in *DefaultPolicy) DeepCopy() *DefaultPolicy {
	if in == nil {
		return nil
	}
	out := new(DefaultPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L7Policy) DeepCopyInto(out *L7Policy) {
	*out = *in
	out.Default = in.Default
	in.UrlFilter.DeepCopyInto(&out.UrlFilter)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L7Policy.
func (in *L7Policy) DeepCopy() *L7Policy {
	if in == nil {
		return nil
	}
	out := new(L7Policy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *URLFilter) DeepCopyInto(out *URLFilter) {
	*out = *in
	if in.Urls != nil {
		in, out := &in.Urls, &out.Urls
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.PodSelector.DeepCopyInto(&out.PodSelector)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new URLFilter.
func (in *URLFilter) DeepCopy() *URLFilter {
	if in == nil {
		return nil
	}
	out := new(URLFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiedNetworkPolicy) DeepCopyInto(out *UnifiedNetworkPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiedNetworkPolicy.
func (in *UnifiedNetworkPolicy) DeepCopy() *UnifiedNetworkPolicy {
	if in == nil {
		return nil
	}
	out := new(UnifiedNetworkPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnifiedNetworkPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiedNetworkPolicyList) DeepCopyInto(out *UnifiedNetworkPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UnifiedNetworkPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiedNetworkPolicyList.
func (in *UnifiedNetworkPolicyList) DeepCopy() *UnifiedNetworkPolicyList {
	if in == nil {
		return nil
	}
	out := new(UnifiedNetworkPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnifiedNetworkPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiedNetworkPolicySpec) DeepCopyInto(out *UnifiedNetworkPolicySpec) {
	*out = *in
	if in.L7Policies != nil {
		in, out := &in.L7Policies, &out.L7Policies
		*out = make([]L7Policy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.PodSelector.DeepCopyInto(&out.PodSelector)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiedNetworkPolicySpec.
func (in *UnifiedNetworkPolicySpec) DeepCopy() *UnifiedNetworkPolicySpec {
	if in == nil {
		return nil
	}
	out := new(UnifiedNetworkPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiedNetworkPolicyStatus) DeepCopyInto(out *UnifiedNetworkPolicyStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiedNetworkPolicyStatus.
func (in *UnifiedNetworkPolicyStatus) DeepCopy() *UnifiedNetworkPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(UnifiedNetworkPolicyStatus)
	in.DeepCopyInto(out)
	return out
}
